name: _spacetime
favicon: null
layout_spectrum: 0.51674
typography_spectrum: 0.82108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
